# Generated by Django 5.1.3 on 2025-02-13 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_admin", "0002_admissionnumber"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SchoolAdmin",
        ),
    ]
