# Generated by Django 5.0 on 2025-01-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parents", "0002_feecategory_feestructure_studentfeepayment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentfeepayment",
            name="due_date",
        ),
        migrations.AddField(
            model_name="feestructure",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
