# Generated by Django 5.0 on 2025-01-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parents", "0003_remove_studentfeepayment_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfeepayment",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
