# Generated by Django 5.0 on 2024-12-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="guardian_name",
        ),
        migrations.AddField(
            model_name="student",
            name="parent_email",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
