# Generated by Django 5.0 on 2024-12-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_remove_student_guardian_name_student_parent_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_number",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_number",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
