# Generated by Django 5.0 on 2024-12-17 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_student_admission_number_and_more"),
        ("teachers", "0003_alter_schoolclass_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="class_assigned",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="teachers.section",
            ),
        ),
    ]
