# Generated by Django 5.0 on 2025-01-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_student_class_assigned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="parent_email",
        ),
        migrations.RemoveField(
            model_name="student",
            name="parent_name",
        ),
    ]
