# Generated by Django 5.0 on 2025-01-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_student_academic_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["roll_number"]},
        ),
    ]
