# Generated by Django 5.0 on 2025-01-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_alter_student_options"),
        ("teachers", "0014_attendance_academic_year"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="student",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("roll_number", "class_assigned", "academic_year")},
        ),
    ]
