# Generated by Django 5.0 on 2024-12-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_superadmin",
        ),
    ]
