# Generated by Django 5.0 on 2024-12-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_otp_customuser_otp_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
