# Generated by Django 5.0 on 2024-12-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="emergency_contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
