# Generated by Django 5.0 on 2024-12-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_emergency_contact_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="reset_password",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
