# Generated by Django 5.0 on 2024-12-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_customuser_reset_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="otp",
        ),
    ]
