# Generated by Django 5.0 on 2024-12-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_otpverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="reset_password",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name="OTPVerification",
        ),
    ]
