# Generated by Django 5.1.3 on 2025-02-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_customuser_reset_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="school_logo",
            field=models.ImageField(blank=True, null=True, upload_to="school_logo/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="school_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="school_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIMARY", "Primary School"),
                    ("SECONDARY", "Secondary School"),
                    ("BOTH", "Both Primary and Secondary"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
