# Generated by Django 5.1.3 on 2025-07-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_customuser_school_logo_customuser_school_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
