# Generated by Django 5.0 on 2024-12-17 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0002_alter_schoolclass_class_teacher_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="schoolclass",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="schoolclass",
            name="class_name",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name="schoolclass",
            name="section",
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_name", models.CharField(max_length=10)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="teachers.schoolclass",
                    ),
                ),
            ],
            options={
                "unique_together": {("school_class", "section_name")},
            },
        ),
    ]
