# Generated by Django 5.0 on 2024-12-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0004_section_student_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolclass",
            name="class_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
