# Generated by Django 5.0 on 2024-12-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0005_alter_schoolclass_class_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="sections",
            field=models.ManyToManyField(
                related_name="teachers", to="teachers.section"
            ),
        ),
    ]
