# Generated by Django 5.0 on 2025-01-07 14:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0007_section_available_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="qualifications",
        ),
        migrations.CreateModel(
            name="TeacherDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "document",
                    models.FileField(
                        upload_to="teacher_documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docs",
                        to="teachers.teacher",
                    ),
                ),
            ],
        ),
    ]
