# Generated by Django 5.0 on 2025-01-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0008_remove_teacher_qualifications_teacherdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
