# Generated by Django 5.0 on 2025-01-11 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0010_section_academic_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolclass",
            name="class_teacher",
        ),
        migrations.AddField(
            model_name="section",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_teacher",
                to="teachers.teacher",
            ),
        ),
    ]
