# Generated by Django 5.0 on 2025-01-13 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0013_attendance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="teachers.academicyear",
            ),
        ),
    ]
