# Generated by Django 5.0 on 2025-01-18 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0015_assignment_remove_teacher_subjects_teacher_subjects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="subjects",
        ),
        migrations.AddField(
            model_name="teacher",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="teachers.subject",
            ),
        ),
    ]
