# Generated by Django 5.0 on 2025-01-18 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0016_remove_teacher_subjects_teacher_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="teachers.subject",
            ),
        ),
    ]
