# Generated by Django 5.0 on 2025-01-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0017_alter_teacher_subject"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Assignment",
        ),
    ]
