# Generated by Django 5.0 on 2025-01-20 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0019_assignment_assignmentsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="class_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_assignments",
                to="teachers.section",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_assignments",
                to="teachers.teacher",
            ),
        ),
    ]
