# Generated by Django 5.1.3 on 2025-01-29 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0021_exam_question_mcqchoice_studentexam_studentanswer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="class_section",
        ),
        migrations.AddField(
            model_name="exam",
            name="class_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_class",
                to="teachers.section",
            ),
        ),
    ]
