# Generated by Django 5.1.3 on 2025-02-03 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_alter_student_unique_together_and_more"),
        ("teachers", "0022_remove_exam_class_section_exam_class_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherStudentChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_recieved", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "reciever",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="students.student",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="send_messages",
                        to="teachers.teacher",
                    ),
                ),
            ],
        ),
    ]
