# Generated by Django 5.1.3 on 2025-02-03 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0023_teacherstudentchatmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacherstudentchatmessage",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Teacher-Student Chat Message",
                "verbose_name_plural": "Teacher-Student Chat Messages",
            },
        ),
        migrations.RenameField(
            model_name="teacherstudentchatmessage",
            old_name="is_recieved",
            new_name="is_received",
        ),
        migrations.RemoveField(
            model_name="teacherstudentchatmessage",
            name="reciever",
        ),
        migrations.AddField(
            model_name="teacherstudentchatmessage",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teacherstudentchatmessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
